/**
 * Axiom Scene Types
 *
 * This file defines the complete data format for an Axiom scene.
 * A scene is pure JSON — no functions, no closures.
 * Every element has an explicit coordinate. No layout engine is involved.
 *
 * This format is designed to be generated by a language model.
 * LLMs: read docs/LLM_PRIMER.md for full authoring instructions.
 *
 * **Format versioning:** `Scene.formatVersion` (default `1`) is bumped only for
 * breaking JSON contract changes. See CHANGELOG.md at the package root.
 */

// CSS color string: "#RRGGBB", "#RGBA", "rgba(r,g,b,a)", "hsl(...)"
export type Color = string

// Canvas 2D font string: "700 18px Inter"
// Format: "[style] [weight] [size]px [family]"
export type FontSpec = string

export type Stroke = {
  color: Color
  width: number
  dash?: number[] // e.g. [4, 4] for dashed line
}

export type Shadow = {
  x: number
  y: number
  blur: number
  color: Color
}

export type TextAlign = 'left' | 'center' | 'right'

/**
 * Text wrapping / measurement backend for `text` nodes.
 * - `canvas`: built-in `measureText` word wrap (default).
 * - `pretext`: [@chenglou/pretext](https://www.npmjs.com/package/@chenglou/pretext) — DOM-free layout, better i18n and line breaks. Requires `maxWidth` and `lineHeight`.
 */
export type TextLayoutEngine = 'canvas' | 'pretext'

// Canvas 2D textBaseline values
export type Baseline = 'top' | 'middle' | 'alphabetic' | 'bottom' | 'hanging'

export type Cursor =
  | 'default'
  | 'pointer'
  | 'grab'
  | 'grabbing'
  | 'crosshair'
  | 'text'
  | 'ns-resize'
  | 'ew-resize'
  | 'none'

// ─── Base properties shared by all node types ─────────────────────────────────

export type BaseProps = {
  // Unique identifier for this node. Used for hit testing, spring targeting,
  // and accessibility. Must be unique within the scene.
  id: string

  // Position relative to the parent node's top-left corner.
  // For top-level nodes, relative to the viewport origin (0, 0).
  x: number
  y: number

  // Global opacity [0, 1]. Multiplied with parent opacity.
  opacity?: number

  // If true, this node participates in hit testing (mouse events).
  interactive?: boolean

  // CSS cursor shown when hovering this node.
  cursor?: Cursor

  // Child nodes. Their x/y are relative to this node's rendered position.
  // When this node is spring-animated, all children move with it.
  children?: SceneNode[]
}

// ─── Node types ───────────────────────────────────────────────────────────────

/**
 * A filled rectangle, optionally with rounded corners.
 * The most common node type — used for cards, buttons, panels, dividers.
 */
export type RectNode = BaseProps & {
  type: 'rect'
  width: number
  height: number
  fill?: Color
  stroke?: Stroke
  radius?: number // corner radius in px
  shadows?: Shadow[]
}

/**
 * Text rendered at a specific position.
 *
 * Font is a Canvas 2D font string: "700 16px Inter"
 * Baseline 'top' means y is the top of the cap height — use this for positioned text.
 * Baseline 'middle' means y is vertically centered — use for labels that must be centered.
 *
 * For multiline text, provide both maxWidth and lineHeight.
 * The renderer will word-wrap and render each line.
 */
export type TextNode = BaseProps & {
  type: 'text'
  content: string
  font: FontSpec
  fill: Color
  align?: TextAlign
  baseline?: Baseline
  maxWidth?: number // wraps text when content exceeds this width
  lineHeight?: number // required when maxWidth is set
  /** When `'pretext'`, uses Pretext for line breaking; `maxWidth` and `lineHeight` are required. */
  textLayout?: TextLayoutEngine
}

/**
 * A circle. x, y refer to the center of the circle.
 */
export type CircleNode = BaseProps & {
  type: 'circle'
  radius: number
  fill?: Color
  stroke?: Stroke
  shadows?: Shadow[]
}

/**
 * A straight line from (x, y) to (x + dx, y + dy).
 * dx, dy are relative offsets from the start point.
 */
export type LineNode = BaseProps & {
  type: 'line'
  dx: number
  dy: number
  stroke: Stroke
}

/**
 * A container with no visual representation.
 * Use for grouping nodes that should move together or share a coordinate origin.
 * Clips children if clipChildren is true.
 */
export type GroupNode = BaseProps & {
  type: 'group'
  children: SceneNode[]
  clipWidth?: number // clip children to this rect
  clipHeight?: number
}

export type SceneNode = RectNode | TextNode | CircleNode | LineNode | GroupNode

// ─── Scene ────────────────────────────────────────────────────────────────────

/**
 * A radial gradient drawn over the background color.
 * cx, cy are 0..1 fractions of viewport width/height.
 * r is a 0..1 fraction of Math.max(viewportWidth, viewportHeight).
 */
export type BackgroundGradient = {
  cx: number
  cy: number
  r: number
  from: Color
  to: Color
}

/**
 * The complete scene definition. This is what an LLM generates.
 * Everything about the visual state of the UI is encoded here.
 */
export type Scene = {
  /**
   * Scene JSON contract version. Omitted means `1`.
   * Increment when breaking changes affect the shape LLMs must emit.
   */
  formatVersion?: number

  // Base background color fill.
  background?: Color

  // Optional radial gradient layered over the background.
  backgroundGradient?: BackgroundGradient

  // All top-level nodes in the scene. Rendered in order (last = topmost).
  nodes: SceneNode[]
}

// ─── Physics ──────────────────────────────────────────────────────────────────

/**
 * Configuration for a spring animation.
 *
 * stiffness: how aggressively the spring pulls toward the target.
 *            Higher = snappier. Typical range: 80–600.
 *
 * damping:   how quickly oscillation decays.
 *            Higher = less bounce. Typical range: 10–40.
 *            For critically damped (no overshoot): damping ≈ 2 * sqrt(stiffness * mass)
 *
 * mass:      how heavy the element feels. Default 1.
 *            Higher = slower, more inertia.
 *
 * Common presets:
 *   Snappy:    { stiffness: 400, damping: 28 }
 *   Default:   { stiffness: 200, damping: 20 }
 *   Gentle:    { stiffness: 120, damping: 18 }
 *   Bouncy:    { stiffness: 200, damping: 10 }
 *   Heavy:     { stiffness: 100, damping: 14, mass: 2 }
 */
export type SpringConfig = {
  stiffness: number
  damping: number
  mass?: number
}
